"use strict";

import { statusCodes, statusMessages } from "necessary";

const { ZERO_0_STATUS_CODE,
        OK_200_STATUS_CODE,
        FOUND_302_STATUS_CODE,
        CREATED_201_STATUS_CODE,
        SEE_OTHER_303_STATUS_CODE,
        FORBIDDEN_403_STATUS_CODE,
        NOT_FOUND_404_STATUS_CODE,
        NO_CONTENT_204_STATUS_CODE,
        BAD_GATEWAY_502_STATUS_CODE,
        BAD_REQUEST_400_STATUS_CODE,
        UNAUTHORIZED_401_STATUS_CODE,
        REQUEST_TIMEOUT_408_STATUS_CODE,
        TOO_MANY_REQUESTS_429_STATUS_CODE,
        SERVICE_UNAVAILABLE_503_STATUS_CODE,
        INTERNAL_SERVER_ERROR_500_STATUS_CODE } = statusCodes,
      { ZERO_0_STATUS_MESSAGE,
        OK_200_STATUS_MESSAGE,
        FOUND_302_STATUS_MESSAGE,
        CREATED_201_STATUS_MESSAGE,
        SEE_OTHER_303_STATUS_MESSAGE,
        FORBIDDEN_403_STATUS_MESSAGE,
        NOT_FOUND_404_STATUS_MESSAGE,
        NO_CONTENT_204_STATUS_MESSAGE,
        BAD_GATEWAY_502_STATUS_MESSAGE,
        BAD_REQUEST_400_STATUS_MESSAGE,
        UNAUTHORIZED_401_STATUS_MESSAGE,
        REQUEST_TIMEOUT_408_STATUS_MESSAGE,
        TOO_MANY_REQUESTS_429_STATUS_MESSAGE,
        SERVICE_UNAVAILABLE_503_STATUS_MESSAGE,
        INTERNAL_SERVER_ERROR_500_STATUS_MESSAGE } = statusMessages;

const statusMap = {
  [ZERO_0_STATUS_CODE]: ZERO_0_STATUS_MESSAGE,
  [OK_200_STATUS_CODE]: OK_200_STATUS_MESSAGE,
  [FOUND_302_STATUS_CODE]: FOUND_302_STATUS_MESSAGE,
  [CREATED_201_STATUS_CODE]: CREATED_201_STATUS_MESSAGE,
  [SEE_OTHER_303_STATUS_CODE]: SEE_OTHER_303_STATUS_MESSAGE,
  [FORBIDDEN_403_STATUS_CODE]: FORBIDDEN_403_STATUS_MESSAGE,
  [NOT_FOUND_404_STATUS_CODE]: NOT_FOUND_404_STATUS_MESSAGE,
  [NO_CONTENT_204_STATUS_CODE]: NO_CONTENT_204_STATUS_MESSAGE,
  [BAD_GATEWAY_502_STATUS_CODE]: BAD_GATEWAY_502_STATUS_MESSAGE,
  [BAD_REQUEST_400_STATUS_CODE]: BAD_REQUEST_400_STATUS_MESSAGE,
  [UNAUTHORIZED_401_STATUS_CODE]: UNAUTHORIZED_401_STATUS_MESSAGE,
  [REQUEST_TIMEOUT_408_STATUS_CODE]: REQUEST_TIMEOUT_408_STATUS_MESSAGE,
  [TOO_MANY_REQUESTS_429_STATUS_CODE]: TOO_MANY_REQUESTS_429_STATUS_MESSAGE,
  [SERVICE_UNAVAILABLE_503_STATUS_CODE]: SERVICE_UNAVAILABLE_503_STATUS_MESSAGE,
  [INTERNAL_SERVER_ERROR_500_STATUS_CODE]: INTERNAL_SERVER_ERROR_500_STATUS_MESSAGE
};

function statusMessageFromStatusCode(statusCode) {
  const statusMessage = statusMap[statusCode];

  return statusMessage;
}

module.exports = {
  statusMessageFromStatusCode
};
